=== Elacity/wiki/metadata/schemas/distribution-right/v1.0/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/Elacity/wiki/main/metadata/schemas/distribution-right/v1.0/schema.json",
  "title": "Distribution Right Metadata",
  "type": "object",
  "properties": {
    "version": {
      "const": "1.0"
    },
    "schema": {
      "const": "https://raw.githubusercontent.com/Elacity/wiki/main/metadata/schemas/distribution-right/v1.0/schema.json"
    },
    "type": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "decimals": {
      "type": "integer",
      "minimum": 0
    },
    "description": {
      "type": "string"
    },
    "image": {
      "type": "string",
      "minLength": 1
    },
    "contentType": {
      "type": "string",
      "enum": [
        "Video",
        "Audio",
        "Image",
        "Text",
        "Other"
      ]
    },
    "properties": {
      "type": "object",
      "properties": {
        "contract": {
          "type": "object",
          "properties": {
            "class": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "identifier": {
              "type": "string"
            },
            "metadata": {
              "type": "object",
              "additionalProperties": true
            },
            "issuedIn": {
              "type": "string"
            },
            "issuer": {
              "type": "string"
            },
            "actedBySubject": {
              "type": "string"
            },
            "actedBy": {
              "type": "string"
            },
            "actedOver": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "actObjects": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "act": {
              "type": "string"
            },
            "beneficiaries": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "actionsIsSubject": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "deonticsIssued": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "role": {
              "type": "string"
            },
            "parties": {
              "type": "object",
              "additionalProperties": true
            },
            "deontics": {
              "type": "object",
              "additionalProperties": true
            },
            "actions": {
              "type": "object",
              "additionalProperties": true
            },
            "objects": {
              "type": "object",
              "additionalProperties": true
            }
          },
          "required": [
            "class",
            "identifier"
          ],
          "additionalProperties": true
        },
        "kid": {
          "type": "string"
        },
        "iscc": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "required": [
        "kid",
        "iscc",
        "title"
      ],
      "additionalProperties": true
    }
  },
  "required": [
    "version",
    "schema",
    "type",
    "name",
    "description",
    "image",
    "properties"
  ],
  "additionalProperties": true,
  "allOf": [
    {
      "if": {
        "required": [
          "contentType"
        ],
        "properties": {
          "contentType": {
            "not": {
              "const": "Video"
            }
          }
        }
      },
      "then": {
        "properties": {
          "properties": {
            "not": {
              "required": [
                "contract"
              ]
            }
          }
        }
      }
    }
  ]
}

=== Elacity/wiki/metadata/schemas/distribution-right/v1.0/example.json
{
  "version": "1.0",
  "schema": "https://raw.githubusercontent.com/Elacity/wiki/main/metadata/schemas/distribution-right/v1.0/schema.json",
  "type": "DistributionRight",
  "name": "Distribution Right",
  "description": "Allow owner to distribute the content via trade",
  "image": "ipfs://QmUCdYfKagTbiFU86ya5HnfASSSQnYX7nttjikvLtJiaBE",
  "properties": {
    "contract": {
      "class": "Distribute",
      "type": "Distribute",
      "identifier": "http://mpeg.org/resell3",
      "actedBy": "http://mpeg.org/Consumer",
      "actedOver": [
        "http://mpeg.org/Video"
      ]
    },
    "kid": "1c84e7e9c77f46418feade114e7eac0e",
    "iscc": "CCWPZDTFVIYEN-CYDMM3ZOV32SH-CDVTU5RNPFOES-CRFYL1RAATD6F",
    "title": "4210523-uhd_3840_2160_24fps"
  }
}
